// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/register.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ExGP.Messages {

  /// <summary>Holder for reflection information generated from auth/register.proto</summary>
  public static partial class RegisterReflection {

    #region Descriptor
    /// <summary>File descriptor for auth/register.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RegisterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNhdXRoL3JlZ2lzdGVyLnByb3RvEg1FeEdQLk1lc3NhZ2VzIkAKD1JlZ2lz",
            "dGVyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRILCgNpZ24YAiABKAkSEQoJcGFz",
            "c19oYXNoGAMgASgJIp4CChBSZWdpc3RlclJlc3BvbnNlEg8KB3N1Y2Nlc3MY",
            "ASABKAgSQAoFZXJyb3IYAiABKA4yMS5FeEdQLk1lc3NhZ2VzLlJlZ2lzdGVy",
            "UmVzcG9uc2UuUmVnaXN0cmF0aW9uRXJyb3ISDQoFZW1haWwYAyABKAkSCwoD",
            "Z2lkGAQgASgJEhMKC3Nlc3Npb25fa2V5GAUgASgJEhIKCmFjY291bnRfaWQY",
            "BiABKAMicgoRUmVnaXN0cmF0aW9uRXJyb3ISEQoNSU5WQUxJRF9FTUFJTBAA",
            "Eg8KC0lOVkFMSURfSUdOEAESDwoLRU1BSUxfVEFLRU4QAhIVChFJTkFQUFJP",
            "UFJJQVRFX0lHThADEhEKDVVOS05PV05fRVJST1IQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ExGP.Messages.RegisterRequest), global::ExGP.Messages.RegisterRequest.Parser, new[]{ "Email", "Ign", "PassHash" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ExGP.Messages.RegisterResponse), global::ExGP.Messages.RegisterResponse.Parser, new[]{ "Success", "Error", "Email", "Gid", "SessionKey", "AccountId" }, null, new[]{ typeof(global::ExGP.Messages.RegisterResponse.Types.RegistrationError) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegisterRequest : pb::IMessage<RegisterRequest> {
    private static readonly pb::MessageParser<RegisterRequest> _parser = new pb::MessageParser<RegisterRequest>(() => new RegisterRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ExGP.Messages.RegisterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterRequest(RegisterRequest other) : this() {
      email_ = other.email_;
      ign_ = other.ign_;
      passHash_ = other.passHash_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterRequest Clone() {
      return new RegisterRequest(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ign" field.</summary>
    public const int IgnFieldNumber = 2;
    private string ign_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ign {
      get { return ign_; }
      set {
        ign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pass_hash" field.</summary>
    public const int PassHashFieldNumber = 3;
    private string passHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PassHash {
      get { return passHash_; }
      set {
        passHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Ign != other.Ign) return false;
      if (PassHash != other.PassHash) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Ign.Length != 0) hash ^= Ign.GetHashCode();
      if (PassHash.Length != 0) hash ^= PassHash.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Ign.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Ign);
      }
      if (PassHash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PassHash);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Ign.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ign);
      }
      if (PassHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PassHash);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterRequest other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Ign.Length != 0) {
        Ign = other.Ign;
      }
      if (other.PassHash.Length != 0) {
        PassHash = other.PassHash;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Ign = input.ReadString();
            break;
          }
          case 26: {
            PassHash = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RegisterResponse : pb::IMessage<RegisterResponse> {
    private static readonly pb::MessageParser<RegisterResponse> _parser = new pb::MessageParser<RegisterResponse>(() => new RegisterResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ExGP.Messages.RegisterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterResponse(RegisterResponse other) : this() {
      success_ = other.success_;
      error_ = other.error_;
      email_ = other.email_;
      gid_ = other.gid_;
      sessionKey_ = other.sessionKey_;
      accountId_ = other.accountId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterResponse Clone() {
      return new RegisterResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private global::ExGP.Messages.RegisterResponse.Types.RegistrationError error_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ExGP.Messages.RegisterResponse.Types.RegistrationError Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 3;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gid" field.</summary>
    public const int GidFieldNumber = 4;
    private string gid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Gid {
      get { return gid_; }
      set {
        gid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_key" field.</summary>
    public const int SessionKeyFieldNumber = 5;
    private string sessionKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SessionKey {
      get { return sessionKey_; }
      set {
        sessionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 6;
    private long accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (Error != other.Error) return false;
      if (Email != other.Email) return false;
      if (Gid != other.Gid) return false;
      if (SessionKey != other.SessionKey) return false;
      if (AccountId != other.AccountId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Gid.Length != 0) hash ^= Gid.GetHashCode();
      if (SessionKey.Length != 0) hash ^= SessionKey.GetHashCode();
      if (AccountId != 0L) hash ^= AccountId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (Error != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Error);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Gid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gid);
      }
      if (SessionKey.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SessionKey);
      }
      if (AccountId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(AccountId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Error);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Gid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gid);
      }
      if (SessionKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionKey);
      }
      if (AccountId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Gid.Length != 0) {
        Gid = other.Gid;
      }
      if (other.SessionKey.Length != 0) {
        SessionKey = other.SessionKey;
      }
      if (other.AccountId != 0L) {
        AccountId = other.AccountId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 16: {
            error_ = (global::ExGP.Messages.RegisterResponse.Types.RegistrationError) input.ReadEnum();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Gid = input.ReadString();
            break;
          }
          case 42: {
            SessionKey = input.ReadString();
            break;
          }
          case 48: {
            AccountId = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the RegisterResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum RegistrationError {
        [pbr::OriginalName("INVALID_EMAIL")] InvalidEmail = 0,
        [pbr::OriginalName("INVALID_IGN")] InvalidIgn = 1,
        [pbr::OriginalName("EMAIL_TAKEN")] EmailTaken = 2,
        [pbr::OriginalName("INAPPROPRIATE_IGN")] InappropriateIgn = 3,
        [pbr::OriginalName("UNKNOWN_ERROR")] UnknownError = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
